const base = "@characters";

export default {
  LOAD_CHARACTERS_REQUEST: `${base}/LOAD_CHARACTERS_REQUEST`,
  LOAD_CHARACTERS_SUCCESS: `${base}/LOAD_CHARACTERS_SUCCESS`,
  LOAD_CHARACTERS_FAIL: `${base}/LOAD_CHARACTERS_FAIL`,
};